### ISSUE TITLE
cli: support pre- and post-execution tasks

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#192]
For example, register a tool that at the end of a stage, generates a `.dot` file describing the workflow of that stage. The tools will be recorded in the `.popper.yml` file by specifying a `post-tasks` entry. For example:

```yaml
exp1:
  stages: [ setup.sh, run.sh, validate.sh ]
  env: ubuntu-16.04
  post-tasks:
    run.sh:
    - <dot-generator-tool> --flag1 --flag2 <args> 
```
