### ISSUE TITLE
cli: support custom paths for pipelines

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#211]
allow a pipeline to be on a custom location, instead of the `pipelines/` or `paper/` subfolders. This should also extend the `popper init` command so that it considers the name argument as a path if it exists:

```bash
popper init [--env] [--stages] [name|path]
```

which checks first if `path` exists and, if it doesn't, it adds it to the `pipelines` folder. For example, if there is an existing pipeline on `ci/`, invoking

```bash
popper init --env=ubuntu-xenial --stages=prepare.sh,run.sh,validate.sh ci/
```

will cause the `.popper.yml` to look like this:

```yaml
ci:
  envs: ubuntu-xenial
  stages: [prepare.sh, run.sh, validate.sh]
  path: ci/
```
