### ISSUE TITLE
cli: add build matrix support

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#212]
Initially, this will be a one-dimensional matrix, which comes directly from a list of environment variables defined on the `.popper.yml` file. For example:

```yaml
myexp:
  envs: ubuntu-xenial
  stages: [setup.sh, run.sh, post-run.sh, validate.sh, teardown.sh]
  vars:
  - CHECK_COVERAGE=0 RUN_POST_ANALYSIS=0
  - CHECK_COVERAGE=0 RUN_POST_ANALYSIS=1
  - CHECK_COVERAGE=1 RUN_POST_ANALYSIS=0
  - CHECK_COVERAGE=1 RUN_POST_ANALYSIS=1
```

The above would execute a pipeline 4 times, one for each set of environment variables.

A new `vars` subcommand will be added, and the `run` and `init` subcommands need to be changed to support this, as well as the `check.py` command.
