### ISSUE TITLE
cli: add support for multiple execution environments

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#213]
Currently, we assume only one environment for each pipeline. Defining multiple environments implicitly adds a new dimension to the execution matrix (#332), so a pipeline definition will change from this:

```yaml
myexp:
  envs: ubuntu-xenial
  stages: [setup.sh, run.sh, post-run.sh, validate.sh, teardown.sh]
```

to this:

```yaml
myexp:
  envs: [fedora-26, ubuntu-xenial]
  stages: [setup.sh, run.sh, post-run.sh, validate.sh, teardown.sh]
```

i.e. `envs` is now a list.

Corresponding changes to the `run`, `init` and `env` subcommands need to be implemented too.
