### ISSUE TITLE
cli: pipeline parametrization and running in docker interact in weird ways

### ISSUE THREAD

**Issue by pseeth** [systemslab/popper#481]
I have  .popper.yml file that looks like this:

```
badge-server-url: http://badges.falsifiable.us
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  my-pipeline:
    envs:
      local/my-environment:
        args: !!set
          --ipc=host: null
          --runtime=nvidia: null
    parameters:
    - par1: var1
    - par1: var2
    - par1: var3
    - par1: var4
    path: pipelines/my-pipeline
    requirements: {}
    stages:
    - train
    - test
    timeout: 0
```

When I run this, something weird happens. The popper run inside the Docker environment does each Job (for var1:4), but then the popper OUTSIDE the docker (which launched it in the first place), goes through and does them all again. You end up with a total of 16 jobs run. Further, the popper run inside the docker keeps overwriting the 0 directory in popper/local_my-environment/0. Once all the parameters have been run inside the docker, it then moves onto the 1 directory and does it all over again. Strange! Not sure if I'm doing something wrong. Let me know if I am! 

Thanks!
