### ISSUE TITLE
cli: create workflow parser library

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#617]
strip out the `cli/popper/parser.py` module and create a standalone library. As part of this, we can define a schema using [`pykwalify`](https://github.com/Grokzen/pykwalify) that allows us to automatically validate a given workflow file. For example:

```yaml
type: map
mapping:
  steps:
    type: seq
    sequence:
    - type: map
      mapping:
        uses:
          type: str
          required: yes
        id:
          type: str
        args:
          type: seq
          sequence:
          - type: str
        runs:
          type: seq
          sequence:
          - type: str
        secrets:
          type: seq
          sequence:
          - type: str
        env:
          type: map
          matching-rule: "any"
          mapping:
            regex;(.+):
              type: str
type: map
mapping:
  options:
    type: map
    mapping:
      secrets:
        type: seq
        sequence:
        - type: str
      env:
        type: map
        matching-rule: "any"
        mapping:
          regex;(.+):
            type: str
```
