### ISSUE TITLE
cli: add YAML syntax similar to HCL

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#773]
add a YAML syntax that is similar to HCL. For example, a workflow similar to the [minimal-python](https://github.com/popperized/popper-examples/blob/master/workflows/minimal-python/main.workflow) one when written in YAML:

```yaml
steps:

- uses: "popperized/bin/curl@master"
  args: [
    "--create-dirs",
    "-Lo workflows/minimal-python/data/global.csv",
    "https://github.com/datasets/co2-fossil-global/raw/master/global.csv"
  ]

- id: 'analysis 1'
  uses: "jefftriplett/python-actions@master"
  args: "workflows/minimal-python/scripts/get_mean_by_group.py"
    "workflows/minimal-python/data/global.csv",
    "5"
  ]

- id: 'analysis 2'
  uses: "jefftriplett/python-actions@master"
  args: "workflows/minimal-python/scripts/analysis2.py"

- uses: "jefftriplett/python-actions@master"
  needs: ['analysis 1', 'analysis 2']
  args: [
    "workflows/minimal-python/scripts/validate_output.py",
    "workflows/minimal-python/data/global_per_capita_mean.csv"
  ]
```

some comments:

  * if no `id` for a step is given, an internal one is generated (e.g. `1` for the first step above).
  * if no `needs` attribute is given for a step, the `steps` list is used to determine the order in which the step is executed. In the example above, `analysis 1` executes after the first step.
  * if a `needs` attribute is given, then that is used to determine the order in which to execute steps. For example, in the above, the last step references `analysis 1` and `analysis 2` as the steps needed to execute before it.
  * all the other attributes of HCL syntax action (`env`, `secrets`, etc..) are supported.

**Comment by JayjeetAtGithub** [comment]
> steps list is used to determine the order in which the step is executed.

@ivotron I am confused about what will be the execution order for the above workflow.  Can you please tell me like how should steps without `needs` attribute be connected to the graph generated by the steps having `needs` attribute?

**Comment by ivotron** [comment]
hey @JayjeetAtGithub, sorry for the confusion.

> Is it like we generate a DAG as far as possible connecting as many steps as possible to and then connect the remaining steps(actions) with the root of the forward edged graph in the order given in which they are given in the `steps` list?

yes. Another way to think about is like this: if a step doesn't have a `needs` entry, it has to wait for all previous steps to finish before it executes. So a more illustrative example (I ignore args for simplicity) would be:

```yaml
steps:

- uses: "popperized/bin/curl@master"

- id: 'analysis'
  uses: "jefftriplett/python-actions@master"

- id: 'I run concurrently with last step'
  needs: ['analysis']
  uses: "docker://alpine:3.8"

- id: 'I have to wait for the above to finish'
  uses: "docker://alpine:3.8"

- id: 'I can run before the above'
  needs: ['analysis']
  uses: "jefftriplett/python-actions@master"
```

using numbers, the order looks like:

```
1 -> 2 -> (3, 5) -> 4
```

note that in the above workflow we can remove the `id` attribute from the last three steps and the order of execution is the same. In general, the goal is to mimic [google cloud build's](https://cloud.google.com/cloud-build/docs/configuring-builds/configure-build-step-order) way of handling this.

please let me know if you have any other question
