### ISSUE TITLE
cli: allow workflow-wide environment variables and secrets

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#825]
Add an `options` section to the workflow (similar to [GCB's](https://cloud.google.com/cloud-build/docs/build-config)) that allows to define environment variables and secrets that are available to all steps in a workflow.

Example workflow:

```yaml
options:
  env:
    FOO: var1
    BAR: var2
  secrets: [SECRET1, SECRET2]

steps:
- uses: docker://alpine:3.11
  runs: sh
  args: "-c 'echo $FOO'"
```
